### ISSUE TITLE
New feature recommendation - random answer generator

### ISSUE THREAD

**Issue by sireteller** [yingmo55/which-language-first#6]
Currently clicking on the option "I don't know, just pick one for me" simply leads to Python, but it could be a fun feature if the option is hooked up to a random generator that picks something different for the user every time. Could also add a button to ask for another language under the randomized result, for even more random if the user isn't satisfied with the first generated result.

**Comment by jccdev45** [comment]
Hi, I'd like to take on this issue if that's alright!

**Comment by yingmo55** [comment]
Thanks for taking an interest in my project! Feel free to work on it & submit a pull request when you are done.
